version: '3.1'

services:
  tws:
    image: bart-ib-docker
    ports:
      - "127.0.0.1:4003:4003"
      - "127.0.0.1:4004:4004"
      - "127.0.0.1:5900:5900"

    #volumes:
    #  - ./IBController.ini:/root/IBC/config.ini
    #  - ./jts.ini:/root/Jts/jts.ini

    environment:
      - TRADING_MODE
      - TWSUSERID
      - TWSPASSWORD
      - VNCPASSWORD

    #secrets:
    #  - ib_password
    #  - vnc_password

#secrets:
#  ib_password:
#    external: true

#  vnc_password:
#    external: true
